spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
            - Path=/api/custumors/**
        - id: r2
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
