spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTUMOR-SERVICE
          predicates:
            Path= /api/custumors/**
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            Path= /api/products/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
